[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "lumache"
authors = [{name = "Alexandre MATHIEU", email = "alexandre.mathieu@cstb.fr"}]
dynamic = ["version", "description"]
